name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: godot-tester
        uses: croconut/godot-tester@v2.5
        with:
          version: 3.4.4
          import-time: 5
          test-dir: res://test
          minimum-pass: 1.00
          
